cats99/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #Routes for (Cats)
  resources :cats
end

cats99/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

cats99/app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :integer          not null, primary key
#  birth_date  :date             not null
#  age         :integer          not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text             not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null

require "action_view"

class Cat < ApplicationRecord
    include ActionView::Helpers::DateHelper

    #Calculate Age Method
    def calculate_age(birth_date)
        age = ((Time.zone.now - birth_date.to_time) / 1.year.seconds).floor
    end

    #Validations
    validates :name, presence: true
    validates :birth_date, presence: true
    validates :sex, presence: true, inclusion: { in: %w(M F), message: "%{value} is not a valid sex"}
    validates :color, presence: true, inclusion: { in: %w(black white orange tabby tuxedo calico red), message: "%{value} is not a valid color"}
end

cats99/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

cats99/app/controllers/cats_controller.rb
class CatsController < ApplicationController
    def index 
        @cats = Cat.all 
        render 'index'
    end

    def show
        @cat = Cat.find_by(id: params[:id])

        render 'show'
    end

    #the actual controller action to create a new cat instance
    def create
        @cat = Cat.new(cat_params)
        @cat.age = @cat.calculate_age(cat_params[:birth_date])

        if @cat.save
            redirect_to cat_url(@cat)
        else
            rendor json: @cat.errors.full_message, status: :unprocessable_entity
        end
    end

    #GET request to the form where you can create a new cat
    def new
        render 'new'
    end

    #GET request to the form where you can edit a cat
    def edit
        @cat = Cat.find_by(id: params[:id])
        render 'edit'
    end

    #actual controller action to edit the cat
    def update
        @cat = Cat.find_by(id: params[:id])

        @cat.age = @cat.calculate_age(cat_params[:birth_date])

        if @cat.update(cat_params)
            redirect_to cat_url(@cat)
        else
            render :edit
        end
    end

    private
    
    def cat_params
        params.require(:cat).permit(:birth_date, :color, :name, :sex, :description)
    end
end

cats99/app/helpers/application_helper.rb
module ApplicationHelper
end

cats99/app/views/cats/edit.html.erb
<form action="<%= cat_url(@cat) %>" method="post">
    <input type="hidden" name="_method" value="patch">
<label>Name:
    <input type="text" name="cat[name]" value="<%= @cat.name %>">
</label>
<br>

<label>Sex:
    <input type="text" name="cat[sex]" value="<%= @cat.sex%>">
</label>
<br>

<label>Birthday:
    <input type="text" name="cat[birth_date]" value="<%= @cat.birth_date%>">
</label>
<br>

<label>Color:
    <input type="text" name="cat[color]" value="<%= @cat.color%>">
</label>
<br>

<label>Description:
    <input type="text" name="cat[description]" value="<%= @cat.description%>">
</label>
<br>

<input type="submit" value="Update User">
</form>

cats99/app/views/cats/index.html.erb
<h1>All the Cats!</h1>

<ul> 
    <% @cats.each do |cat| %>
        <h3>Name: <%= cat.name%> </h3>
        <li>Birthday: <%= cat.birth_date %></li>
        <li>Age: <%=  cat.age %> </li>
        <li>Color: <%= cat.color %> </li>
        <li>Sex: <%=  cat.sex %> </li>
        <li>Description: <%= cat.description%>
        
        <li> <a href="<%= cat_url(cat)%>"> <%= cat.name %>'s Individual page</a> </li>
        <br>
    <% end %>
</ul>

cats99/app/views/cats/new.html.erb
<form action="<%= cats_url %>" method="post">
<label>Name:
    <input type="text" name="cat[name]">
</label>
<br>

<label>Sex:
    <input type="radio" name="cat[sex]" value="M"> Male
    <input type="radio" name="cat[sex]" value="F"> Female
</label>
<br>

<label>Birthday:
    <input type="text" name="cat[birth_date]">
</label>
<br>

<label>Color:
    <select name = "cat[color]">
        <option disabled selected>--Please Select--</option>
        <option value="black">Black</option>
        <option value="white">White</option>
        <option value="orange">Orange</option>
        <option value="tabby">Tabby</option>
        <option value="tuxedo">Tuxedo</option>
        <option value="calico">Calico</option>
        <option value="red">Red</option>
    </select>

</label>
<br>

<label>Description:
    <input type="text" name="cat[description]">
</label>
<br>

<input type="submit" value="Create User">
</form>

cats99/app/views/cats/show.html.erb
<h1> <%= @cat.name %> </h1>

<h2> Birth Day: <%= @cat.birth_date %> </h2>
<h3> Age: <%= @cat.age %> </h3>
<h4> Color: <%= @cat.color %> </h4>
<h5> Sex: <%= @cat.sex %> </h5>

<p> <%= @cat.description %> </p>

cats99/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cats99</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>